# Generated by Django 5.0 on 2023-12-31 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=8, null=True)),
                ('adresse', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Represantant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tickets.objet')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=200)),
                ('problem', models.CharField(max_length=200)),
                ('note', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('status', models.CharField(default='EN_COURS', max_length=20)),
                ('observation', models.TextField(max_length=500)),
                ('cree_a', models.DateTimeField(auto_now_add=True)),
                ('modifie_a', models.DateTimeField(auto_now=True)),
                ('sortie_a', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recus', to='tickets.categorie')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recus', to='tickets.client')),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recus', to='tickets.objet')),
                ('represantant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recus', to='tickets.represantant')),
            ],
        ),
    ]
