# Generated by Django 4.2 on 2024-01-07 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': '2- Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': '5- Clients'},
        ),
        migrations.AlterModelOptions(
            name='famille',
            options={'verbose_name_plural': '1- Familles'},
        ),
        migrations.AlterModelOptions(
            name='historicalrecu',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical recu', 'verbose_name_plural': 'historical 6- Récus'},
        ),
        migrations.AlterModelOptions(
            name='objet',
            options={'verbose_name_plural': '3- Objets'},
        ),
        migrations.AlterModelOptions(
            name='recu',
            options={'verbose_name_plural': '6- Récus'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': '4- Status'},
        ),
        migrations.AlterField(
            model_name='historicalrecu',
            name='represantant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recu',
            name='represantant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Represantant',
        ),
    ]
