# Generated by Django 5.0 on 2023-12-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recu',
            old_name='deposit',
            new_name='accompte',
        ),
        migrations.RenameField(
            model_name='recu',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='recu',
            old_name='problem',
            new_name='probleme',
        ),
        migrations.AlterField(
            model_name='recu',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recu',
            name='status',
            field=models.CharField(choices=[('EN_COURS', 'En Cours'), ('REPARE', 'Réparé'), ('NON_REPARE', 'Non Réparé'), ('SORTIE_REPARE', 'Sortie Réparé'), ('SORTIE_NON_REPARE', 'Sortie Non Réparé')], default='EN_COURS', max_length=20),
        ),
    ]
