# Generated by Django 4.2 on 2024-01-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_categorie_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
