# Generated by Django 5.0 on 2023-12-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_deposit_recu_accompte_rename_price_recu_prix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recu',
            name='sortie_a',
        ),
    ]
