# Generated by Django 4.2 on 2024-01-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_status_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='default',
            new_name='par_default',
        ),
    ]
